[package]
name = "np"
description = "Numpy-like package in Rust"
license = "BSD-3-Clause"
version = "0.1.2"
authors = ["Bayu Aldi Yansyah <bayualdiyansyah@gmail.com>"]
edition = "2018"
homepage = "https://github.com/pyk/np"
repository = "https://github.com/pyk/np"

[dependencies]
num = "0.2.0"
